# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9bc4d5865f4a02321c4fac5a8f13acd9f5151e395153eb178bb3465c91285132ca1b38d88807630e03311e70f64f8399390a116caddc0e39426ad0add75ce06

test:
  secret_key_base: fb3db0c9fbac9c5780d3fb78fce82969bcb5200798e0e7d0e2128585f62cb35595e4105a371f99d4e16b48f9e3142b3a7ee3219d7162cb12c8fb79b6a8ef0d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
